apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kinetica-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./samples/k8s/flux/marketplace/aks"
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-kineticadb
    namespace: flux-system
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: operator-values
  patches:
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: kinetica-operators
      patch: |
        - op: add
          path: /spec/values/ingress-nginx.controller.service.annotations/service.beta.kubernetes.io~1azure-dns-label-name
          value: "${AZURE_DNS_LABEL_NAME}"

---

