apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kinetica-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./samples/k8s/flux/marketplace/aks"
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-kineticadb
    namespace: flux-system
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: operator-values
  patches:
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: kinetica-operators
      patch: |
        - op: add # service.beta.kubernetes.io/azure-load-balancer-ipv4
          path: /spec/values/ingress-nginx/controller/service/annotations/service.beta.kubernetes.io~1azure-load-balancer-ipv4
          value: "${AZURE_INTERNAL_LB_IP}"
        - op: add # service.beta.kubernetes.io/azure-load-balancer-internal-subnet
          path: /spec/values/ingress-nginx/controller/service/annotations/service.beta.kubernetes.io~1azure-load-balancer-internal-subnet
          value: "${AZURE_INTERNAL_LB_SUBNET}"

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  path: "./samples/k8s/flux/velero"
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-kineticadb
    namespace: flux-system
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: operator-values
