apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kinetica-operators
  namespace: flux-system
spec:
  interval: 5h0m0s
  url: https://kineticadb.github.io/charts/latest
