apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  install:
    createNamespace: true
  releaseName: velero
  targetNamespace: velero
  interval: 1m
  chart:
    spec:
      chart: velero
      version: 7.1.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  values:
    logLevel: debug
    configuration:
      backupStorageLocation:
        - provider: azure
          bucket: ${BACKUP_CONTAINER_NAME}
          config:
            storageAccount: ${STORAGE_ACCOUNT_NAME}
            resourceGroup: ${RESOURCE_GROUP_NAME}
            useAAD: "true"
      volumeSnapshotLocation:
        - provider: azure
          config:
            resourceGroup: ${RESOURCE_GROUP_NAME}
            subscriptionId: ${SUBSCRIPTION_ID}

    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.10.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      secretContents:
        cloud: |
          AZURE_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
          AZURE_RESOURCE_GROUP=${RESOURCE_GROUP_NAME}
          AZURE_CLOUD_NAME=AzurePublicCloud
    podLabels:
      azure.workload.identity/use: "true"
    serviceAccount:
      server:
        name: velero
        annotations:
          azure.workload.identity/client-id: "${AZURE_WORKLOAD_IDENTITY_CLIENTID}"
